[package]
name = "sgx-io-uring-ocalls"
version = "1.0.0"
authors = ["The Occlum team"]

[lib]
crate-type = ["staticlib"]

[workspace]

[dependencies]
sgx_types = { path = "../../rust-sgx-sdk/sgx_types" }
libc = "0.2"
